- aiter/ops/triton/moe_op.py
- op_tests/triton/test_moe.py
- requirements.txt
> Add Triton MoE Kernel

- csrc/py_itfs_cu/asm_fmoe.cpp
The MOE fp8 smoothquant test was failing. I traced to this tile size heuristic which returns SelectTile sizes that do not currently have an implementation.
The workaround here is to force 512 size for now but this heuristic will need to be reworked to be more flexible based on the currently available range of implementations.
> Workaround for failing Fmoe-g1u1 fp8smoothquant test

- op_tests/triton/test_rmsnorm.py
All tests passed locally with this compiler version: triton-lang/triton@c4c8bac, but the CI is failing with the commented unit tests. So I'm putting it here until we find the reason.
> Comment Triton RMSNorm unit tests causing the CI to fail

- aiter/ops/triton/gemm_a8w8.py
- op_tests/triton/test_gemm_a8w8.py
> Add GEMM A8W8 Triton Kernel

- README.md
The installation section is slightly misleading about pulling the submodule and which directory to step into for building the python wheel.
Though it might be trivial, the command
```
git submodule sync ; git submodule update --init --recursive
```
can only be run after stepping into the base repo. The existing steps are written as if it is run outside of the base.
It seems to suggest that we need to step into `aiter/aiter` to build but actually `cd aiter` refers to the base aiter git repo.
Make sure the the 2nd command will not be run if 1st one is not successful.
> Update Installation Step in README.md

- aiter/aot/triton_compile.py
Avoid AITER build error on Triton 3.3
> remove kernel_suffix: compatible to triton 3.3

- op_benchmarks/triton/bench_mha.py
- op_benchmarks/triton/bench_moe.py
- op_benchmarks/triton/bench_moe_align_block_size.py
- op_benchmarks/triton/bench_pa_decode.py
- op_benchmarks/triton/bench_pa_prefill.py
- op_benchmarks/triton/utils/benchmark_utils.py
- op_benchmarks/triton/utils/model_configs.json
- op_tests/triton/test_moe_align_block_size.py
Coauthored with @Chi-Chu319 
This PR adds benchmarking for triton kernels with scripts located at op_benchmarks/triton. Benchmarking ready for mha kernel (aiter.ops.triton.mha) and moe kernel (aiter.ops.triton.moe_op) with scripts bench_mha.py and bench_moe.py. 
Easy way to get realistic benchmarking results (with shapes from existing models) with the kernels is to use the -model "model_name(s)" command line argument with both of these scripts. For example:
python $AITERDIR/op_benchmarks/triton/bench_mha.py -model llama3
gives results:
use -help to get information about the available model configs additional command line options. One can add new model configs by modifying the op_benchmarks/triton/utils/model_configs.json.
> Triton kernel benchmarking

- aiter/ops/triton/moe_op_silu_fused.py
- op_tests/triton/test_moe.py
Migrated from https://github.com/ROCm/triton/pull/710
Implemented the moe gemm + silu_and_mul fusion. The logic of the fusion is:
- Load the b pointer in a interleaved manner, `[0, 0 + BLOCK_N // 2, 1, 1 + BLOCK_N // 2, 3, 3 + BLOCK_N // 2, ..., BLOCK_N // 2 - 1, BLOCK_N]`
- After the gemm, we can simply [reshape](https://triton-lang.org/main/python-api/generated/triton.language.reshape.html) the gemm product to (BLOCK_SIZE_M, BLOCK_SIZE_N // 2, 2) and [split](https://triton-lang.org/main/python-api/generated/triton.language.split.html) to obtain the silu_acc and mul_acc
- Apply silu on silu_acc and multiply it with mul_acc
- Store the result
You can benchmark the fused kernel (moe gemm + silu activation) with the `-use_silu_activation` flag.
Implemented a separate `silu_and_mul` kernel. …
> silu_and_mul fused moe

- aiter/jit/core.py
when using "ray", it may has multiple MainProcess
this code may cause file not found issue
( one process remove library, and the other need the library ) so remove it to fix the problem
> Fix random file not found error

- csrc/py_itfs_ck/moe_sorting_kernels.cu
topk-weights in dtype bf16 will cause numeric issues silently. This PR adds the check
cc @carlushuang
> add asser to check topk-weights dtype

- op_tests/__init__.py
- op_tests/triton/__init__.py
- op_tests/triton/utils/__init__.py
Enable modular imports for op_tests.triton. 
This change improves test modularity and allows clean imports like:
`from op_tests.triton import mla_decode_ref_fn`
> Enable structured imports for op_tests.triton.utils

- op_tests/__init__.py
- op_tests/triton/__init__.py
- op_tests/triton/utils/__init__.py
Reverts ROCm/aiter#293
this one break all functions in aiter
> Revert "Enable structured imports for op_tests.triton.utils"

- aiter/ops/triton/mha.py
We have the following simple flow of computation
```python
qk += tl.dot(q, k)
qk *= SCALE
m_ij = tl.maximum(m_i, tl.max(qk, 1))
p = exp2(qk - m_ij)
```
The max separates multiplication of SCALE and subtract of max apart, therefore we need both v_fma and v_sub instructions.
This PR changes the computation into
```python
qk += tl.dot(q, k)
m_ij = tl.maximum(m_i, tl.max(qk, 1))
q_shifted = qk * SCALE - (m_ij * SCALE)[:, None]
```
m_ij * SCALE is a single f_mul. Then q_shifted can be lowered to
```asm
v_fma v_qk, v_qk, s_scale, -m_ij*SCALE
```
v_sub is folded into v_fma
> [Triton] [FA] Compute max after SCALE multiplication

- aiter/ops/triton/mha.py
When the head size gets too large, we get out of shared memory errors. So reduce BLOCK_N if head size is greater than 160. Also BLK_SLICE_FACTOR = 1 causes mismatches
> fix oom and other bugs

- op_tests/test_moe_ep.py
This test mainly simulates the ep test on a GPU with gpu rank `ep-1`, so the mask should set the **last ep size** experts to 1. In addition, when constructing the weight, each GPU should only need to allocate the weight of **ep size experts**.
> [MoE] refine moe ep test

- aiter/ops/triton/rmsnorm.py
- aiter/ops/triton/routing.py
- op_benchmarks/triton/bench_routing.py
- op_tests/triton_tests/test_rmsnorm.py
- op_tests/triton_tests/test_routing.py
```
python3 -m pytest op_tests/triton_tests/test_routing.py -k test_routing_sigmoid_top1
python3 -m pytest op_tests/triton_tests/test_rmsnorm.py -k test_rms_norm_dynamic_per_token_fp8_quant
```
fused routing
```
python3 op_benchmarks/triton/bench_routing.py
(vllm) sijiac@devgpu013:aiter  (main)$ python3 op_benchmarks/triton/bench_routing.py
=== PREFILL SHAPEs ===
M=1024 K=5120 N=128 TOPK=1, ms_eager_time=0.048, ms_triton_time=0.049, ms_compile_time=0.051, speedup_vs_eager: 0.979, speedup_vs_compile: 1.043
best triton config:
M=1024 K=5120 N=16 TOPK=1, ms_eager_time=0.035, ms_triton_time=0.023, ms_compile_time=0.079, speedup_vs_eager: 1.485, speedup_vs_compile: 3.374
best triton config:
M=2048 K=5120 N=128 TOPK=1, ms_eager_time=0.058, ms_triton_time=0.052, ms_compile_time=0.055, …
```
> [Triton] fused routing and fused quant kernels

- aiter/jit/core.py
- Get AITER_ROOT_DIR while aiter is not installed
- skip import module while not is_python_module
> Fix c++ api use case

- aiter/ops/triton/gemm_afp4wfp4.py
- op_tests/triton_tests/test_gemm_afp4wfp4.py
This PR fixes memory access error due to parsing faulty `EVEN_K`, which originates from checking only `K % BLOCK_SIZE_K == 0` for `EVEN_K`.
This PR also includes a heuristic function `get_splitk`, of determining `SPLITK_BLOCK_SIZE, BLOCK_SIZE_K, NUM_KSPLIT` such that it makes `EVEN_K == True` as much as possible
> [Triton] Fix gemm mxfp4 for memory access error due to parsing faulty EVEN_K

- aiter/ops/triton/quant.py
This PR tunes the Triton mxfp4 quantization kernel and adds the workaround for the 32-bit stride issue where (M*N) > (2^31 - 1) causes integer overflow in pointer arithmetic. The pointer arithmetic for the kernel is now in int64.
The update includes larger block size for the N dimension (multiple blocks of 32), multiple iterations per program with pipelining and parameter tuning. 
Performance numbers for bfloat16 to mxfp4 on mi350:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<body link="#0563C1" vlink="#954F72">
M | N | Orig. GB/s | New Code GB/s | Speedup
-- | -- | -- | -- | --
1 | 16384 | 10.9 | 15.3 | 1.41
4 | 16384 | 40.9 | 57.3 | 1.40
8 | 16384 …
> TRITON: Tune mxfp4 quantization kernel

- aiter/jit/core.py
- aiter/ops/triton/mha.py
As per title.
Aiter should be installable/usable with `GPU_ARCHS="gfx950"`.
> [Fix] aiter installed/usable with gfx950

- csrc/ck_gemm_a8w8_blockscale/gemm_a8w8_blockscale_tune.py
Per title. When `tuned_gemm_file` does not exist, the returned dataframe is missing column `cu_num`, which is present in `a8w8_blockscale_tuned_gemm.csv`. This makes the script fails to run.
This PR fixes the issue.
> fix: add missing column `cu_num` for `gemm_a8w8_blockscale_tune.py`

- csrc/kernels/attention.cu
On gfx950, use __builtin_amdgcn_mfma_f32_16x16x32_f16, __builtin_amdgcn_mfma_f32_16x16x32_bf16 instead of __builtin_amdgcn_mfma_f32_16x16x16f16, __builtin_amdgcn_mfma_f32_16x16x16bf16_1k
> gfx950: Use 16x16x32 MFMA for regular tensor too

- csrc/include/custom_all_reduce.cuh
convert dtype between half and float by using __half2float and __float2half
> [fix]: replace static_cast<float>(half)

- aiter/jit/utils/chip_info.py
- aiter/jit/utils/cpp_extension.py
In my production environment, we don't have rocm/bin in PATH, but the rocm is installed at the place _find_rocm_home can find it.
So add executable_path function to lookup the executable in ROCM/bin dir when it is not found in the PATH
> Find executable in rocm home when not found in PATH

- aiter/jit/core.py
Without this change, I am seeing system-wide install of aiter (python3 setup.py install) misidentified as setup.py develop. This leads to AITER_ASM_DIR being incorrectly set, which leads to a general failure when aiter can't find precompiled kernel .co objects.
> Improved detection of setup.py install

- aiter/ops/quant.py
- aiter/ops/triton/moe_op.py
- aiter/ops/triton/moe_op_e2e.py
- aiter/ops/triton/moe_op_gelu.py
- aiter/ops/triton/moe_op_silu_fused.py
- aiter/ops/triton/quant.py
- op_tests/triton_tests/test_quant.py
1. Add int8 quantization ops
2. Add doc
3. Fix per_token_fp8 testcase
> [TRITON]: Quantization updates(add int8 and use common fp8 dtypes)

- csrc/include/custom_all_reduce.cuh
- csrc/kernels/custom_all_reduce.cu
- csrc/py_itfs_cu/asm_communication.cu
change allreduce kernal namespace from vllm to aiter
> [fix]: change ar namespace

- csrc/kernels/fmla/fwd_prefill_kernels.cu
1. support merge seqlen and qk ratio by tensor view transform
2. optimize vgpr spill by replace static parity loops with dynamic parity loops
3. use enum class XqaStrategy to choose the method of merging seqlen and qk ratio
> xiangxli merge seqlen and qk ratio by tensor view transform

- aiter/fused_moe.py
- csrc/kernels/topk_softmax_kernels.cu
**Description:**
This PR improves the `topksoftmax` kernel by:
* Tuning `WARPS_PER_TB` to boost occupancy and throughput.
* Eliminating the explicit precision conversion step before launch, since the kernel now handles all necessary type casting internally (significant performance gains on bf16 and fp16).
*No functional changes.*
**Note:** The planned topk optimization was not included because it introduced precision issues that would require additional handling—and thus too much overhead. @valarLip @junhaha666
> Optimize topksoftmax WARPS_PER_TB for higher occupancy and remove redundant precision conversion

- csrc/include/custom_all_reduce.cuh
add 2 new kernel for all_reduce optimize
> [fea]: new kernel for allreduce optimize

- csrc/cpp_itfs/pa/pa_kernels.cuh
Fix the following warning.
```
csrc/cpp_itfs/pa/pa_kernels.cuh:403:54: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
403 |     float exp_sum[GQA_RATIO_LOOP][MTP_PER_THREAD] = {0.0f};
```
> fix missing-braces warning during compilation

- csrc/kernels/topk_softmax_kernels.cu
- Fuse k-select with softmax so we compute exp() only for top-K
- Widen vector loads to 32B
MI300A
N=64, K=5-8: ~1.12× - 1.53x kernel speedup; 
N=256, K=5-8: ~0.97× - 1.13x kernel speedup; 
N=512, K=5-8: ~0.98x - 1.76x kernel speedup;
> Optimize topksoftmax: top-K-only softmax + 32B vector loads

- op_tests/triton_tests/test_batched_gemm_a8w8.py
- op_tests/triton_tests/test_batched_gemm_afp4wfp4.py
- op_tests/triton_tests/test_batched_gemm_afp4wfp4_pre_quant.py
- op_tests/triton_tests/test_batched_gemm_bf16.py
- op_tests/triton_tests/test_gemm_a16w16.py
- op_tests/triton_tests/test_gemm_a16w16_gated.py
- op_tests/triton_tests/test_gemm_a8w8.py
- op_tests/triton_tests/test_gemm_a8w8_blockscale.py
- op_tests/triton_tests/test_gemm_a8w8_per_token_scale.py
- op_tests/triton_tests/test_gemm_afp4wfp4.py
- op_tests/triton_tests/test_gemm_afp4wfp4_pre_quant_atomic.py
Add test cases covering non-TN layout scenarios to Triton GEMMS.
Tests for TT, NN and NT layouts have been added. For some GEMMS, those layouts are tested on a smaller test suite to reduce CI runtime.
Pass.
> [TRITON] Add non-TN layout tests to Triton GEMMs

- op_tests/triton_tests/test_mha.py
This PR disable Triton MHA bkwd unit tests. They are currently failing due to accuracy mismatches after a Triton compiler change.
Marked test with pytest.skip
Change is to a test case itself
Passes locally
> [TRITON]: Disable mha bkwd UT

- aiter/jit/core.py
When running gemm_tuner, there are some errors with getHipblasltKernelName. 
We found getHipblasltKernelName define in python side do not have input/return annotation, but in kernel, it returns **string** witch not supported by custom op. Disable it in wrapper.
> Disable getHipblasltKernelName to fix tune error

- aiter/aot/aot.py
```sh
docker run -it --device /dev/dri --device /dev/kfd --network host --ipc host  --group-add video --security-opt seccomp=unconfined  -v /mnt/nvme1/david/:/workspace/ -v /mnt/nvme1/data:/data -w /workspace rocm/private:latest
pip uninstall aiter
pip list |grep aiter # show no more aiter package
cd /opt/aiter/aiter/jit
rm -rf *.so
rm -rf build
python3 -m aiter.aot.aot --out-dir /opt/aiter/aiter/jit/
export JIT_WORKSPACE_DIR=/opt/aiter/aiter/jit/
python3 setup.py develop 
cd /opt/vllm/
rm -rf build 
rm -rf .deps
rm -rf vllm/.*so 
rm -rf vllm.egg-info/
rm -rf /root/.cache/vllm
python3 setup.py install --root=/opt/vllm/
``` 
```yml
"module_mha_varlen_fwd",
"module_quant",
"module_rmsnorm",
"module_rocsolgemm",
"module_hipbsolgemm",
"module_rope_general_fwd",
"module_rope_pos_fwd", …
```
> add aot kernel build for deepseek 

- csrc/py_itfs_cu/fmha_bwd_pre_post_kernel_generate.py
block size is removed in ck_tile::make_kernel in https://github.com/ROCm/composable_kernel/pull/2594, we need update related code in aiter to fix the build error.
> Update  ck_tile::make_kernel interface to fix the build

- hsa/gfx942/fmha_v3_bwd/codegen.py
- hsa/gfx942/fmha_v3_fwd/codegen.py
- hsa/gfx950/fmha_v3_bwd/codegen.py
- hsa/gfx950/fmha_v3_fwd/codegen.py
Use env var to index asm path
get AITER_ASM_DIR from std::getenv()
pass AITER standard CI and cpp api smoke test
> Use env var to index asm path

- aiter/ops/triton/fused_kv_cache.py
- op_tests/triton_tests/test_fused_kv_cache.py
This PR enables RoPE + zeros + reshape_and_cache fusion for Llama 70B (both with and without `--kv-cache-dtype fp8 ` works)
> [Triton] add fused_qk_rope_reshape_and_cache

- csrc/kernels/solver/Makefile
- csrc/kernels/solver/README.md
- csrc/kernels/solver/lapack_sytrd.py
- csrc/kernels/solver/sytrd_benchmark.cu
- csrc/kernels/solver/sytrd_kernels.cu
Provide an efficient HIP implementation of symmetric tridiagonal reduction (SYTRD) algorithm optimized to outperforms rocSOLVER on AMD GPU. The SYTRD algorithm is one of LAPACK functions, which is used by symmetric eigenvalue/vector decomposition and shampoo optimizer.
The optimized SYTRD implementation incorporates the following enhancements::
- various kernel fusions for reduce_sum, gemv and element-wise operations
- specialized single-wavefront fused kernel for efficient handling of small matrices
- vectorized load/store
- several rocblas functions are called for outer product of vectors `ger` and matrix multiplication `gemm`
A benchmark code is included to validate correctness and compare performance against rocSOLVER.
Accuracy is verified and performance speedup is achieved for a …
> Add hip kernels for symmetric matrix tridiagonalization

- csrc/kernels/custom_all_reduce.cu
allreduce coredump after using torch::from_blob without clone()
add clone() back
run ut test
pass, no coredump
> [fix]: access dangling ptr in ar interface

- aiter/jit/core.py
Custom op will miss passing the args when SymInt=0, leading error. We make SymInt=None in custom op schema to solve it
> Fix rmsnorm2dFusedAddQuant error since custom op SymInt issue

- aiter/ops/mha.py
Torch did not correctly allocate as contiguous before the custom op calls, we got un-contiguous tensor in custom op, and triton kernel convert it to fp32 to cause accuracy issue.
> Fix torch contiguous issue

- aiter/jit/core.py
- aiter/jit/utils/cpp_extension.py
Using unordered sets instead of a ordered (sorted list for e.g.) produces non-determinism in the build system. This patch avoids that.
- [+] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.
> Ninja build non-determinism fix

- aiter/ops/mha.py
- csrc/include/rocm_ops.hpp
- csrc/include/torch/mha_fwd.h
- csrc/include/torch/mha_varlen_fwd.h
- csrc/py_itfs_ck/mha_fwd_kernels.cu
- csrc/py_itfs_ck/mha_varlen_fwd_kernels.cu
- csrc/py_itfs_cu/asm_mha_fwd.cu
- csrc/py_itfs_cu/asm_mha_varlen_fwd.cu
- op_tests/test_mha.py
- op_tests/test_mha_varlen.py
Sequence Padding for FMHA Forward - Adapts to the new Composable Kernel (CK) padding API to support sequence padding. - Enables efficient attention computation for batches with variable sequence lengths by ignoring padded tokens.
- Batch Mode (mha_fwd)
- Adds two new optional parameters to control padding:
- cu_seqlens_q: Specifies the cumulative sequence lengths for query tensors.
- cu_seqlens_kv: Specifies the cumulative sequence lengths for key/value tensors.
- Group Mode (mha_varlen_fwd) 
- Adds two new optional parameters to manage padding based on physical length (including padded tokens): 
- cu_seqlens_q_padded: The cumulative physical sequence lengths for the query. - cu_seqlens_k_padded: The cumulative physical sequence lengths for the key/value.
- Limitations
- Forward Pass …
>     feat(mha): Add sequence padding support for CK FMHA forward
