ROCm/aiter

- aiter/fused_moe_bf16_asm.py
- aiter/fused_moe_gelu.py
- aiter/jit/core.py
- aiter/jit/optCompilerConfig.json
- aiter/ops/moe_op.py
- aiter/ops/moe_sorting.py
- aiter/test_common.py
- csrc/include/moe_ck.h
- csrc/include/moe_sorting.h
- csrc/kernels/topk_softmax_kernels.cu
- csrc/py_itfs_ck/moe_kernels.cu
- csrc/py_itfs_ck/moe_sorting_kernels.cu
- csrc/pybind/moe_ck_pybind.cu
- csrc/pybind/moe_sorting_pybind.cu
- csrc/rocm_ops.cpp
- op_tests/test_moe_ep.py
- op_tests/test_moe_sorting.py
This reverts commit 218bbfa6e5d11e4ce365fa37f59b17ba9c04a02b.
> Revert "Revert "moe_sorting_update (#110)" (#117)"

- aiter/ops/triton/rmsnorm.py
- op_tests/triton/test_rmsnorm.py
Adds the base and fused add versions of RMSNorm Triton kernels.
> Add Triton RMSNorm Kernels

- aiter/ops/triton/moe_align_block_size.py
- op_tests/triton/test_moe_align_block_size.py
Add moe_align_block_size Triton Kernel
> Add MoE align block size Triton Kernel

- aiter/ops/triton/norm.py
- op_tests/triton/test_layernorm.py
Add Triton fused add LayerNorm Kernel
> Add Triton fused add LayerNorm Kernel

- aiter/ops/triton/pa_decode.py
- op_tests/triton/test_pa_decode.py
Add paged attention decode Triton Kernels.
> Add paged attention decode Triton Kernels

- aiter/ops/moe_op.py
> fix the return type of CK MoE

- aiter/ops/mha.py
- op_tests/test_mha.py
- op_tests/test_mha_varlen.py
This issue casue by this PR https://github.com/ROCm/aiter/pull/192
After this PR, following command should all pass
pytest op_tests/test_mha.py
pytest op_tests/test_mha_varlen.py
> Fix bug of incorrect incorrect dout shape

- aiter/ops/triton/pa_prefill.py
- op_tests/triton/test_pa_prefill.py
I'm putting this PR up, but we still need to implement the reference for the unit tests. Currently, all the tests do is call the Triton Kernels and pass if they run without errors.
> Add paged attention prefill Triton Kernels

- op_tests/triton/test_quant.py
Disable some tests that are failing the comparison against torch ref
> Disable some Triton quant tests

- aiter/ops/rope.py
- aiter/rotary_embedding.py
- csrc/include/rocm_ops.hpp
- csrc/include/rope.h
- csrc/include/rope_common.h
- csrc/kernels/rope_pos_fwd_kernels.cu
- op_tests/test_rope.py
> Implement One Channel Version of RoPE with Positions and Offsets.

- csrc/kernels/binary_operator.cu
case(m, n, 1), (n, 1), (m, 1, p, q) support, optimize naive broadcast case by using vectorization and unrolling 8
> [feat]: support elementwise (m,n,1) and (n,1) broadcast case

- aiter/ops/triton/moe_op.py
This pr remaps the XCD for moe, http://github.com/ROCm/triton/blob/main_perf/python/perf-kernels/gemm.py#L94
The logic:
The pid m and n are grouped to access the adjacent tiles on the same XCD so it promotes the L2 usage
> XCD remapping for moe

- aiter/jit/optCompilerConfig.json
- aiter/ops/mha.py
- csrc/cpp_itfs/mha_fwd_generate.py
- csrc/include/mha_common.h
- csrc/include/mha_fwd.h
- csrc/kernels/mha_common.cu
- csrc/py_itfs_ck/mha_fwd_kernels.cu
- csrc/py_itfs_ck/mha_varlen_fwd_kernels.cu
- setup.py
enable fmha fwd aiter api 
exclude fa v3 bwd while prebuild
> Add fmha fwd aiter api 

- aiter/ops/triton/gemm_a8w8_blockscale.py
- op_tests/triton/test_gemm_a8w8_blockscale.py
Add GEMM_A8W8_Blockscale Triton Kernel
> Add GEMM_A8W8_Blockscale Triton Kernel

- aiter/jit/optCompilerConfig.json
- op_tests/test_mha_varlen.py
change rounding method according to environment variable
> Change MHA fwd default rounding to RTZ

- aiter/ops/triton/mha.py
- op_tests/triton/test_mha.py
fixed the causal mha seq_q < seq_k and added corresponding tests
> fixed the causal mha seq_q < seq_k and added corresponding tests

- csrc/kernels/binary_operator.cu
- op_tests/test_aiter_add.py
fix elementwise error in case broadcast at middle dim
> [fix]: elementwise broadcast (m, 1, k) error

- op_tests/triton/test_pa_decode.py
- op_tests/triton/test_pa_prefill.py
Added input_helper so benchmark can use that
> added input_helper for pa

- op_benchmarks/triton/bench_gemm_a8w8.py
- op_benchmarks/triton/utils/benchmark_utils.py
- op_tests/triton/test_gemm_a8w8.py
This PR adds the benchmark for GEMM A8W8 with the following changes as well:
1. Updated `benchmark_utils.py` s.t. prettytable imported only when necessary, otherwise it will fail when reusing the functions within.
2. Update `test_gemm_a8w8.py` to reuse functions.
> [TRITON] gemm_a8w8 benchmark

- aiter/ops/triton/batched_gemm_bf16.py
- op_tests/triton/test_batched_gemm_bf16.py
Add Batched GEMM Bf16 Triton Kernel
> [TRITON] Add Batched GEMM Bf16 Triton Kernel

- aiter/ops/triton/batched_gemm_a8w8.py
- op_tests/triton/test_batched_gemm_a8w8.py
Add Batched GEMM A8W8 Triton Kernel
> [TRITON] Add Batched GEMM A8W8 Triton Kernel

- aiter/ops/triton/mha.py
remove the old if condition in the causal masking and do the mask computation unconditionally. Though this will unconditionally compute mask_partial at runtime, the causal for loop does not have the if-else block any more, which helps instruction scheduling and register pressure.
> [Triton] [mha] Remove if-else block in the causal loop

- aiter/ops/triton/rmsnorm.py
- op_benchmarks/triton/bench_rmsnorm.py
- op_tests/triton_tests/test_rmsnorm.py
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/vigokhal/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/vigokhal/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
</style>
</head>
<body link="#467886" vlink="#96607D">
<span data-teams=true>
M          N       Triton GB/s
--
0    4096.0   4096.0  3131.146892
1    4096.0   8192.0  3910.909510
2    4096.0  16384.0  3618.011399
3    4096.0   4096.0  2122.593308
4    4096.0   6144.0  3372.796878
5  …
> [TRITON]: Add RMSNorm Fwd Benchmark

- aiter/ops/triton/mha.py
This reverts commit 70ae241a4d58ce4c05ab6e9ba37838923623e2b5.
The computation in the commit for mi_j are not mathematically equivalent and causes some UTs to fail
> Revert "Compute max after multiplying SCALE (#333)"

- op_benchmarks/triton/bench_rope.py
[TRITON] fix bug for rope benching script
> Triton rope

- aiter/ops/triton/rope.py
- aiter/rotary_embedding.py
- op_benchmarks/triton/bench_rope.py
- op_tests/triton_tests/test_rope_triton.py
- enable rotary_embedding triton interface
- benchmark RoPE triton kernels
- RoPE triton kernels optimization
- fix bugs in RoPE triton kernels
There are some issues regarding submodule conflicts in https://github.com/ROCm/aiter/pull/382 so this PR is created to redo everything in https://github.com/ROCm/aiter/pull/382 except the submodule conflicts is resolved. This PR also resolves test case failure in https://github.com/ROCm/aiter/pull/382
https://github.com/ROCm/aiter/pull/382 will be closed without merging.
> [TRITON] RoPE fwd

- aiter/ops/triton/batched_gemm_a8w8.py
- aiter/ops/triton/batched_gemm_bf16.py
- aiter/ops/triton/gemm_a16w16.py
- aiter/ops/triton/gemm_a8w8.py
- aiter/ops/triton/gemm_a8w8_blockscale.py
- op_tests/op_benchmarks/triton/bench_gemm_a16w16.py
- op_tests/op_benchmarks/triton/bench_gemm_a8w8.py
- op_tests/op_benchmarks/triton/bench_gemm_a8w8_blockscale.py
- op_tests/triton_tests/test_batched_gemm_a8w8.py
- op_tests/triton_tests/test_batched_gemm_bf16.py
- op_tests/triton_tests/test_gemm_a16w16.py
- op_tests/triton_tests/test_gemm_a8w8.py
- op_tests/triton_tests/test_gemm_a8w8_blockscale.py
Most frameworks provide a tensor to return the output in.
> [TRITON][GEMM] Add support for inplace output

- aiter/ops/triton/rope.py
- op_tests/op_benchmarks/triton/bench_rope.py
- op_tests/triton_tests/test_rope_triton.py
This PR added NEOX rotate style and accepts cases where Q and K have GQA layout, this PR also fixes some masking issues.
> [Triton] RoPE Dev

- aiter/ops/triton/mha.py
- op_tests/triton_tests/test_mha.py
match mha api between ck and triton
> [Triton] Match API

- aiter/ops/triton/mha.py
Fixing NUM_Q_HEADS - 1 to NUM_Q_HEADS in remap_xcd in _attn_fwd.
> fix NUM_Q_HEADS - 1 in remap_xcd in _attn_fwd

- aiter/jit/utils/chip_info.py
Minor nit, found while debugging vLLM AITER failure
> Fix error message for rocminfo

- .github/workflows/sglang_downstream.yaml
Currently, the sglang ci test will fail if the PR is from a forked repo: https://github.com/ROCm/aiter/actions/runs/16713430160/job/47389197041?pr=763#step:5:293
> Fix issues in sglang ci test when it's from a forked repo.

- aiter/jit/core.py
- aiter/jit/utils/cpp_extension.py
- csrc/cpp_itfs/utils.py
- op_tests/cpp/mha/build_mha.sh
update c++17 to c++20, because ck use c++20 now
> update ck and compiler to c++20

- csrc/include/custom_all_reduce.cuh
fix custom all reduce precision error
add device sync at the end of 1 stage ar kernel
inference test done, benchserving test done
pass, bug fixed
> [fix]: custom_allreduce precision bug

- aiter/__init__.py
- aiter/jit/utils/torch_guard.py
- aiter/ops/mha.py
> Fix mha running without bwd and torch 2.9 in compatible

- csrc/cpp_itfs/mha_bwd_generate.py
- csrc/cpp_itfs/mha_fwd_generate.py
Fix module import path in mha cpp api codegen script
Fix module index path
> Fix FA codegen import path

- aiter/ops/gemm_op_a4w4.py
- csrc/py_itfs_cu/asm_gemm_a4w4.cu
- op_tests/test_gemm_a4w4.py
> fix fp4 gemm precision issue

- aiter/ops/custom_all_reduce.py
- csrc/include/rocm_ops.hpp
- csrc/kernels/cache_kernels.cu
- csrc/kernels/custom_all_reduce.cu
- op_tests/test_kvcache.py
> kvcache_minor_opt

- aiter/ops/moe_op.py
fix typo that cause moe always build all instances.
> moe_op fix typo

- aiter/jit/core.py
> AITER_JIT_DIR

- csrc/include/warp_sort.h
- csrc/kernels/topk_softmax_kernels_group.cu
This PR fixes a correctness bug in the group Top-K kernel. 
The fix reduces the latency from ~9 ns to ~6 ns on MI300A (token < 512). For the same configuration, the sglang kernel measures ~16 ns.
> grouped topk bug fixed

- op_tests/triton_tests/test_gemm_a8w8.py
> [TRITON]: Disable shape for a8w8(Failing due to compiler bug)

- aiter/jit/core.py
- aiter/jit/utils/chip_info.py
> Atom compile mode stuck when tracing

- aiter/utility/base_tuner.py
- csrc/ck_batched_gemm_a8w8/batched_gemm_a8w8_tune.py
- csrc/ck_gemm_a4w4_blockscale/gemm_a4w4_blockscale_tune.py
- hsa/gfx942/fmoe_2stages/tune.py
- hsa/gfx950/fmoe_2stages/tune.py
update asm splitk tuning as there are some changes in kernel csv
1. fix errRatio in batched_gemm_a8w8
2. update fmoe tune.py on gfx950
3. clean code
> fix asm splitk tune in gemm_a4w4_blockscale

- aiter/jit/core.py
- aiter/ops/mha.py
> Fix sglang acc issue by inplace all ops

- op_tests/test_mha_varlen.py
CMD: AITER_LOG_MORE=1  python3 op_tests/test_mha_varlen.py -b 1 -nh 16 -mha mqa -d 192 -dv 128 -s 14000,14000  -c
> update ck and test_mha_varlen for mha perf

- setup.py
Include psutil in setup.py dependencies
Add 'psutil' to the 'install_requires' section in setup.py to ensure it is installed as a dependency.
> Include psutil in setup.py dependencies

- csrc/ck_gemm_moe_2stages_codegen/gemm_moe_ck2stages.cu
- csrc/ck_gemm_moe_2stages_codegen/gen_instances.py
fix moe stage2 aot prebuild bugs
> fix moe stage2 when aot prebuild

- aiter/dist/parallel_state.py
- op_tests/multigpu_tests/test_quick_all_reduce.py
1.During the rebase process, I accidentally deleted a line of code, which caused the QR fails.
2.The test_qr function was modeled after test_cr, and pytest couldn't test it.
> [fix] fix quickreduce condition and ci

- .githooks/pre-commit
- csrc/cpp_itfs/utils.py
> enhance pre-commit script

- aiter/fused_moe.py
- aiter/jit/core.py
- csrc/include/rocm_ops.hpp
> remove runtime call to inspect.signature

- aiter/ops/gradlib.py
- csrc/include/rocm_ops.hpp
- gradlib/csrc/hipbsolgemm.cu
- gradlib/include/hipbsolgemm.cuh
- op_tests/test_gemm.py
- op_tests/test_gemm_a8w8.py
> Revert "add hipblaslt swizzle and its unitest"

- aiter/ops/topk.py
> 085 fix topk

- aiter/ops/topk.py
- csrc/kernels/moe_fused_gate.cu
> 085 fix topk2

- csrc/kernels/topk_softmax_kernels_group.cu
(check `us_aiter`)
1.2~1.3x boost for small size
up to 1.5x boost for large size
- use `rcp` for fast divide
- use `exp2` for fast transcendental
- use `v_med3` for group score sorting
- remove some unnecessary if...else.... branching 
- rearrange sorting to reduce VALU
Before:
this PR: 
commit:https://github.com/ROCm/aiter/pull/1101/commits/d5e8ae5e7c8c9239054c6e0dd48b8014fefbdeab further reduce ALU
> topk further optimization for group topk case

- .github/scripts/aiter_test.sh
- .github/scripts/build_triton.sh
- .github/scripts/clean_up_rocm.sh
- .github/workflows/aiter-test.yaml
- .github/workflows/triton-test.yaml
- .github/workflows/vllm_benchmark.yaml
Related to https://github.com/ROCm/frameworks-internal/issues/12993, https://github.com/ROCm/frameworks-internal/issues/12994
> Migrate Aiter test CI to Github actions

- aiter/ops/triton/fused_fp8_quant.py
- aiter/ops/triton/fused_qk_concat.py
This PR includes:
fused input_layernorm + per_token_fp8_quant
fused q_a_layernorm + kv_a_layernorm
tunned fused_qk_rope_cat_and_cache_mla (for bs=256, execution time goes from 24 ~ 27 us to 14 ~15 us)
> [Triton] Shaoclee/085 triton fusion

- aiter/utility/base_tuner.py
- aiter/utility/mp_tuner.py
- csrc/ck_batched_gemm_a8w8/batched_gemm_a8w8_tune.py
- csrc/ck_batched_gemm_bf16/batched_gemm_bf16_tune.py
- csrc/ck_gemm_a4w4_blockscale/gemm_a4w4_blockscale_tune.py
- csrc/ck_gemm_a8w8/gemm_a8w8_tune.py
- csrc/ck_gemm_a8w8_blockscale/gemm_a8w8_blockscale_tune.py
- csrc/ck_gemm_a8w8_bpreshuffle/gemm_a8w8_bpreshuffle_tune.py
- hsa/gfx942/fmoe_2stages/tune.py
refactor fmoe log info and tuner log info
> add tuning summary of shapes that are tuned successfully or failed.
